### ISSUE TITLE
Different format for content possible?

### ISSUE THREAD

**Issue by rchrdnsh** [wiziple/gatsby-plugin-intl#14]
It seems that content is split up based on language. My content team does not work this way at all, and would make it difficult to work with them on content and translations this way:

Rather then this (Please support yaml as well, please):

```yaml
en:
  title: English words

vn:
  title: Vietnamese words
```

they prefer to work like this:

```yaml
title:
  en: English words
  vn: vietnames words
```

...where the separation of concerns is based upon the same piece of content, rather than the arbitrary concept of the language.

It makes sense to me as well, being a react developer, where I don't separate html, css and js, but rather combine them together and makes separations based upon the idea of a component, rather than arbitrary languages.

I hope that makes sense, and that it might be possible to so :-)
